# Generated by Django 3.1 on 2021-09-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20210902_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='法定代表人',
        ),
    ]
