# Generated by Django 3.1 on 2021-10-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0019_auto_20211010_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation_tag_sub',
            name='original_response',
            field=models.CharField(default='NULL', max_length=500),
        ),
    ]
