# Generated by Django 3.1 on 2021-10-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0021_auto_20211012_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_relation',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='company_relation',
            name='percent_total',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Value listed in QCC API response, carried over for data completeness.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='company_relation',
            name='registered_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
