# Generated by Django 3.1 on 2021-10-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0023_error_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='error_report',
            name='error_type',
            field=models.CharField(default='NULL', max_length=15),
            preserve_default=False,
        ),
    ]
