# Generated by Django 3.1 on 2021-10-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0026_auto_20211018_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_relation',
            name='percent_total',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Value listed in QCC API response, carried over for data completeness.', max_digits=6, null=True),
        ),
    ]
