# Generated by Django 3.1 on 2021-10-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0027_auto_20211018_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_relation',
            name='company_code',
            field=models.IntegerField(default=0, help_text='Value listed in QCC API response, carried over for data completeness.'),
        ),
    ]
