# Generated by Django 3.1 on 2021-10-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0034_auto_20211019_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='relations_ping',
        ),
    ]
