# Generated by Django 3.1 on 2021-11-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0036_company_relations_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
