# Generated by Django 3.1 on 2021-11-02 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0037_company_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='figure_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=200)),
                ('econ_kind', models.CharField(default='NULL', help_text='Value listed in QCC API response, carried over for data completeness.', max_length=200)),
                ('percent', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=8, null=True)),
                ('percent_total', models.DecimalField(blank=True, decimal_places=5, help_text='Value listed in QCC API response, carried over for data completeness.', max_digits=8, null=True)),
                ('org', models.IntegerField(default=0, help_text='Value listed in QCC API response, carried over for data completeness.')),
                ('company_code', models.IntegerField(default=0, help_text='Value listed in QCC API response, carried over for data completeness.')),
                ('shouldcapi', models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True)),
                ('stockrightnum', models.CharField(default='NULL', help_text='Value listed in QCC API response, carried over for data completeness.', max_length=200)),
                ('detailcount', models.IntegerField(default=0, help_text='Value listed in QCC API response, carried over for data completeness.')),
                ('shortstatus', models.CharField(default='在业', help_text='Value listed in QCC API response, carried over for data completeness.', max_length=200)),
                ('stocktype', models.CharField(default='NULL', help_text='Value listed in QCC API response, carried over for data completeness.', max_length=200)),
                ('investtype', models.CharField(default='NULL', help_text='Value listed in QCC API response, carried over for data completeness.', max_length=200)),
                ('registered_cap', models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True)),
                ('detaillist', models.CharField(default='NULL', help_text='Value listed in QCC API response, carried over for data completeness.', max_length=200)),
                ('type', models.CharField(default='NULL', help_text='Value listed in QCC API response, carried over for data completeness.', max_length=200)),
                ('pulled_date', models.DateField(auto_now_add=True)),
                ('origin_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='mainsite.company')),
                ('tags', models.ManyToManyField(to='mainsite.relation_tag_sub')),
                ('target_figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Figure', to='mainsite.individual')),
            ],
        ),
    ]
