"""
Django settings for qcc_project project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '90rclz4w1_=kbtr^@95st%$p3t4cp#$5o%_!)u8my!gi)r$9@s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'www.simiangolden.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainsite',
    'functions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'qcc_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates')),],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'NAME' : "Sitemaps",
        'APP_DIRS': True,
    },
]


WSGI_APPLICATION = 'qcc_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

#local
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'qcc_mk2',
        'USER': 'qcc_server',
        'PASSWORD': '6Ndtcx2859xsUkMgCFY9',
        'HOST': 'localhost',
        'PORT': '9999',
    }
}

#online

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'qcc_mk2',
        'USER': 'qcc_server',
        'PASSWORD': '6Ndtcx2859xsUkMgCFY9',
        'HOST': 'crosbysn-2455.postgres.pythonanywhere-services.com',
        'PORT': '12455',
    }
}
'''

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

company_empty_string = "NULL"

figure_fields   = [
    '法定代表人',
    '经营者'
]

date_fields     = [
    '成立日期',
    '核准日期'
]

company_model_translations = {
    '主办券商' : ' ',
    '人员规模' : ' Staff size',
    '企业名称' : ' Company Name',
    '企业类型' : ' Type of enterprise',
    '企业网址' : ' ',
    '会计事务所' : ' ',
    '做市商' : ' ',
    '公司传真' : ' ',
    '公司注册地址' : ' ',
    '公司电子邮箱' : ' ',
    '公司电话' : ' ',
    '办公地址' : ' ',
    '办公地址邮编' : ' ',
    '参保人数' : ' Number of participants',
    '实缴资本' : ' Paid-in capital',
    '工商注册号' : ' Business Registration Number',
    '币种' : ' ',
    '律师事务所' : ' ',
    '总经理' : ' ',
    '成立日期' : ' Date of establishment',
    '所属地区' : ' District belong to',
    '所属行业' : ' Industry',
    '挂牌日期' : ' ',
    '是否上市' : ' ',
    '曾用名' : ' Former name',
    '机构名称' : ' ',
    '机构状态' : ' ',
    '机构简称' : ' ',
    '机构类型大类' : ' ',
    '机构类型小类' : ' ',
    '经营者' : 'Operator',
    '核准日期' : ' Approved date',
    '法定代表人' : ' Legal Representative',
    '注册地址' : ' Registered Address',
    '注册地址邮编' : ' ',
    '注册资本' : ' Registered capital',
    '注册资本万元' : ' ',
    '登记机关' : ' Registration authority',
    '登记状态' : ' Registration status',
    '纳税人识别号' : ' Taxpayer Identification Number',
    '纳税人资质' : ' Taxpayer qualification',
    '组织机构代码' : ' Organization Code',
    '经营范围' : ' Business Scope',
    '统社会信用代码' : ' Unified Social Credit Code',
    '职工人数' : ' ',
    '英文全称' : ' ',
    '英文名' : ' English Name',
    '英文简称' : ' ',
    '营业期限' : ' Operating period',
    '董事会秘书' : ' ',
    '董事长' : ' ',
    '董秘传真' : ' ',
    '董秘联系电话' : ' ',
    '董秘邮箱' : ' ',
    '证券代表' : ' ',
    '证券代表传真' : ' ',
    '证券代表电话' : ' ',
    '证券代表邮箱' : ' ',
    '进出口企业代码' : ' Import and export enterprise code',
}

company_field_names = ['统社会信用代码', '注册资本', '组织机构代码', ' 企业类型', '所属行业', '人员规模', '英文名', '注册地址', '经营范围', '企业名称', '登记状态', '实缴资本', '工商注册号', '营业期限', '所属地区', '参保人数', '成立日期', '核准日期', '纳税人识别号', '纳税人资质', '登记机关', '曾用名', '进出口企业代码', '主办券商', '企业网址', '会计事务所', '做市商', '公司传真', '公司注册地址', '公司电子邮箱', '公司电话', '办公地址', '办公地址邮编', '币种', '律师事务所', '总经理', '挂牌日期', '是否上市', '机构名称', '机构状态', '机构简称', '机构类型大类', '机构类型小类', '注册地址邮编', '注册资本万元', '职工人数', '英文全称', '英文简称', '董事会秘书', '董事长', '董秘传真', '董秘联系电话', '董秘邮箱', '证券代表', '证券代表传真', '证券代表电话', '证券代表邮箱', '电话', '邮箱', '官网', '地址', '简介',]
TEMPLATE_STRING_IF_INVALID = ""
subregion_codes = {'g_AH': ['/g_AH_340100', '/g_AH_340200', '/g_AH_340300', '/g_AH_340400', '/g_AH_340500', '/g_AH_340600', '/g_AH_340700', '/g_AH_340800', '/g_AH_341000', '/g_AH_341100', '/g_AH_341200', '/g_AH_341300', '/g_AH_341500', '/g_AH_341600', '/g_AH_341700', '/g_AH_341800'], 'g_BJ': ['/g_BJ_110101', '/g_BJ_110102', '/g_BJ_110105', '/g_BJ_110106', '/g_BJ_110107', '/g_BJ_110108', '/g_BJ_110109', '/g_BJ_110111', '/g_BJ_110112', '/g_BJ_110113', '/g_BJ_110114', '/g_BJ_110115', '/g_BJ_110116', '/g_BJ_110117', '/g_BJ_110118', '/g_BJ_110119'], 'g_CQ': ['/g_CQ_500101', '/g_CQ_500102', '/g_CQ_500103', '/g_CQ_500104', '/g_CQ_500105', '/g_CQ_500106', '/g_CQ_500107', '/g_CQ_500108', '/g_CQ_500109', '/g_CQ_500110', '/g_CQ_500111', '/g_CQ_500112', '/g_CQ_500113', '/g_CQ_500114', '/g_CQ_500115', '/g_CQ_500116', '/g_CQ_500117', '/g_CQ_500118', '/g_CQ_500119', '/g_CQ_500120', '/g_CQ_500151', '/g_CQ_500152', '/g_CQ_500153', '/g_CQ_500154', '/g_CQ_500155', '/g_CQ_500156', '/g_CQ_500229', '/g_CQ_500230', '/g_CQ_500231', '/g_CQ_500233', '/g_CQ_500235', '/g_CQ_500236', '/g_CQ_500237', '/g_CQ_500238', '/g_CQ_500240', '/g_CQ_500241', '/g_CQ_500242', '/g_CQ_500243'], 'g_FJ': ['/g_FJ_350100', '/g_FJ_350200', '/g_FJ_350300', '/g_FJ_350400', '/g_FJ_350500', '/g_FJ_350600', '/g_FJ_350700', '/g_FJ_350800', '/g_FJ_350900'], 'g_GS': ['/g_GS_620100', '/g_GS_620200', '/g_GS_620300', '/g_GS_620400', '/g_GS_620500', '/g_GS_620600', '/g_GS_620700', '/g_GS_620800', '/g_GS_620900', '/g_GS_621000', '/g_GS_621100', '/g_GS_621200', '/g_GS_622900', '/g_GS_623000'], 'g_GD': ['/g_GD_440100', '/g_GD_440200', '/g_GD_440300', '/g_GD_440400', '/g_GD_440500', '/g_GD_440600', '/g_GD_440700', '/g_GD_440800', '/g_GD_440900', '/g_GD_441200', '/g_GD_441300', '/g_GD_441400', '/g_GD_441500', '/g_GD_441600', '/g_GD_441700', '/g_GD_441800', '/g_GD_441900', '/g_GD_442000', '/g_GD_445100', '/g_GD_445200', '/g_GD_445300'], 'g_GX': ['/g_GX_450100', '/g_GX_450200', '/g_GX_450300', '/g_GX_450400', '/g_GX_450500', '/g_GX_450600', '/g_GX_450700', '/g_GX_450800', '/g_GX_450900', '/g_GX_451000', '/g_GX_451100', '/g_GX_451200', '/g_GX_451300', '/g_GX_451400'], 'g_GZ': ['/g_GZ_520100', '/g_GZ_520200', '/g_GZ_520300', '/g_GZ_520400', '/g_GZ_520500', '/g_GZ_520600', '/g_GZ_522300', '/g_GZ_522600', '/g_GZ_522700'], 'g_HAIN': ['/g_HAIN_460100', '/g_HAIN_460200', '/g_HAIN_460300', '/g_HAIN_460400', '/g_HAIN_469000'], 'g_HB': ['/g_HB_130100', '/g_HB_130200', '/g_HB_130300', '/g_HB_130400', '/g_HB_130500', '/g_HB_130600', '/g_HB_130700', '/g_HB_130800', '/g_HB_130900', '/g_HB_131000', '/g_HB_131100'], 'g_HLJ': ['/g_HLJ_230100', '/g_HLJ_230200', '/g_HLJ_230300', '/g_HLJ_230400', '/g_HLJ_230500', '/g_HLJ_230600', '/g_HLJ_230700', '/g_HLJ_230800', '/g_HLJ_230900', '/g_HLJ_231000', '/g_HLJ_231100', '/g_HLJ_231200', '/g_HLJ_232700'], 'g_HEN': ['/g_HEN_410100', '/g_HEN_410200', '/g_HEN_410300', '/g_HEN_410400', '/g_HEN_410500', '/g_HEN_410600', '/g_HEN_410700', '/g_HEN_410800', '/g_HEN_410900', '/g_HEN_411000', '/g_HEN_411100', '/g_HEN_411200', '/g_HEN_411300', '/g_HEN_411400', '/g_HEN_411500', '/g_HEN_411600', '/g_HEN_411700', '/g_HEN_419000'], 'g_HUB': ['/g_HUB_420100', '/g_HUB_420200', '/g_HUB_420300', '/g_HUB_420500', '/g_HUB_420600', '/g_HUB_420700', '/g_HUB_420800', '/g_HUB_420900', '/g_HUB_421000', '/g_HUB_421100', '/g_HUB_421200', '/g_HUB_421300', '/g_HUB_422800', '/g_HUB_429000'], 'g_HUN': ['/g_HUN_430100', '/g_HUN_430200', '/g_HUN_430300', '/g_HUN_430400', '/g_HUN_430500', '/g_HUN_430600', '/g_HUN_430700', '/g_HUN_430800', '/g_HUN_430900', '/g_HUN_431000', '/g_HUN_431100', '/g_HUN_431200', '/g_HUN_431300', '/g_HUN_433100'], 'g_JS': ['/g_JS_320100', '/g_JS_320200', '/g_JS_320300', '/g_JS_320400', '/g_JS_320500', '/g_JS_320600', '/g_JS_320700', '/g_JS_320800', '/g_JS_320900', '/g_JS_321000', '/g_JS_321100', '/g_JS_321200', '/g_JS_321300'], 'g_JX': ['/g_JX_360100', '/g_JX_360200', '/g_JX_360300', '/g_JX_360400', '/g_JX_360500', '/g_JX_360600', '/g_JX_360700', '/g_JX_360800', '/g_JX_360900', '/g_JX_361000', '/g_JX_361100'], 'g_JL': ['/g_JL_220100', '/g_JL_220200', '/g_JL_220300', '/g_JL_220400', '/g_JL_220500', '/g_JL_220600', '/g_JL_220700', '/g_JL_220800', '/g_JL_222400'], 'g_LN': ['/g_LN_210100', '/g_LN_210200', '/g_LN_210300', '/g_LN_210400', '/g_LN_210500', '/g_LN_210600', '/g_LN_210700', '/g_LN_210800', '/g_LN_210900', '/g_LN_211000', '/g_LN_211100', '/g_LN_211200', '/g_LN_211300', '/g_LN_211400'], 'g_NMG': ['/g_NMG_150100', '/g_NMG_150200', '/g_NMG_150300', '/g_NMG_150400', '/g_NMG_150500', '/g_NMG_150600', '/g_NMG_150700', '/g_NMG_150800', '/g_NMG_150900', '/g_NMG_152200', '/g_NMG_152500', '/g_NMG_152900'], 'g_NX': ['/g_NX_640100', '/g_NX_640200', '/g_NX_640300', '/g_NX_640400', '/g_NX_640500'], 'g_QH': ['/g_QH_630100', '/g_QH_630200', '/g_QH_632200', '/g_QH_632300', '/g_QH_632500', '/g_QH_632600', '/g_QH_632700', '/g_QH_632800'], 'g_SD': ['/g_SD_370100', '/g_SD_370200', '/g_SD_370300', '/g_SD_370400', '/g_SD_370500', '/g_SD_370600', '/g_SD_370700', '/g_SD_370800', '/g_SD_370900', '/g_SD_371000', '/g_SD_371100', '/g_SD_371300', '/g_SD_371400', '/g_SD_371500', '/g_SD_371600', '/g_SD_371700'], 'g_SH': ['/g_SH_310101', '/g_SH_310104', '/g_SH_310105', '/g_SH_310106', '/g_SH_310107', '/g_SH_310109', '/g_SH_310110', '/g_SH_310112', '/g_SH_310113', '/g_SH_310114', '/g_SH_310115', '/g_SH_310116', '/g_SH_310117', '/g_SH_310118', '/g_SH_310120', '/g_SH_310151'], 'g_SX': ['/g_SX_140100', '/g_SX_140200', '/g_SX_140300', '/g_SX_140400', '/g_SX_140500', '/g_SX_140600', '/g_SX_140700', '/g_SX_140800', '/g_SX_140900', '/g_SX_141000', '/g_SX_141100'], 'g_SAX': ['/g_SAX_610100', '/g_SAX_610200', '/g_SAX_610300', '/g_SAX_610400', '/g_SAX_610500', '/g_SAX_610600', '/g_SAX_610700', '/g_SAX_610800', '/g_SAX_610900', '/g_SAX_611000'], 'g_SC': ['/g_SC_510100', '/g_SC_510300', '/g_SC_510400', '/g_SC_510500', '/g_SC_510600', '/g_SC_510700', '/g_SC_510800', '/g_SC_510900', '/g_SC_511000', '/g_SC_511100', '/g_SC_511300', '/g_SC_511400', '/g_SC_511500', '/g_SC_511600', '/g_SC_511700', '/g_SC_511800', '/g_SC_511900', '/g_SC_512000', '/g_SC_513200', '/g_SC_513300', '/g_SC_513400'], 'g_TJ': ['/g_TJ_120101', '/g_TJ_120102', '/g_TJ_120103', '/g_TJ_120104', '/g_TJ_120105', '/g_TJ_120106', '/g_TJ_120110', '/g_TJ_120111', '/g_TJ_120112', '/g_TJ_120113', '/g_TJ_120114', '/g_TJ_120115', '/g_TJ_120116', '/g_TJ_120117', '/g_TJ_120118', '/g_TJ_120119'], 'g_XJ': ['/g_XJ_650100', '/g_XJ_650200', '/g_XJ_650400', '/g_XJ_650500', '/g_XJ_652300', '/g_XJ_652700', '/g_XJ_652800', '/g_XJ_652900', '/g_XJ_653000', '/g_XJ_653100', '/g_XJ_653200', '/g_XJ_654000', '/g_XJ_654200', '/g_XJ_654300', '/g_XJ_659000'], 'g_XZ': ['/g_XZ_540100', '/g_XZ_540200', '/g_XZ_540300', '/g_XZ_540400', '/g_XZ_540500', '/g_XZ_540600', '/g_XZ_542500'], 'g_YN': ['/g_YN_530100', '/g_YN_530300', '/g_YN_530400', '/g_YN_530500', '/g_YN_530600', '/g_YN_530700', '/g_YN_530800', '/g_YN_530900', '/g_YN_532300', '/g_YN_532500', '/g_YN_532600', '/g_YN_532800', '/g_YN_532900', '/g_YN_533100', '/g_YN_533300', '/g_YN_533400'], 'g_ZJ': ['/g_ZJ_330100', '/g_ZJ_330200', '/g_ZJ_330300', '/g_ZJ_330400', '/g_ZJ_330500', '/g_ZJ_330600', '/g_ZJ_330700', '/g_ZJ_330800', '/g_ZJ_330900', '/g_ZJ_331000', '/g_ZJ_331100']}


searchform_null = 'NULL'
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
