# Generated by Django 3.2.9 on 2021-11-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_remove_index_pages_last_page_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='skipped_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_string', models.CharField(max_length=40)),
                ('error_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
