# Generated by Django 3.1 on 2021-09-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('统社会信用代码', models.CharField(max_length=200)),
                ('注册资本', models.CharField(max_length=200)),
                ('组织机构代码', models.CharField(max_length=200)),
                ('企业类型', models.CharField(max_length=200)),
                ('所属行业', models.CharField(max_length=200)),
                ('人员规模', models.CharField(max_length=200)),
                ('英文名', models.CharField(max_length=200)),
                ('注册地址', models.CharField(max_length=200)),
                ('经营范围', models.CharField(max_length=200)),
                ('企业名称', models.CharField(max_length=200)),
                ('登记状态', models.CharField(max_length=200)),
                ('实缴资本', models.CharField(max_length=200)),
                ('工商注册号', models.CharField(max_length=200)),
                ('营业期限', models.CharField(max_length=200)),
                ('所属地区', models.CharField(max_length=200)),
                ('参保人数', models.CharField(max_length=200)),
                ('成立日期', models.DateField()),
                ('核准日期', models.DateField()),
                ('纳税人识别号', models.CharField(max_length=200)),
                ('纳税人资质', models.CharField(max_length=200)),
                ('登记机关', models.CharField(max_length=200)),
                ('曾用名', models.CharField(max_length=200)),
                ('进出口企业代码', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ownership_through_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_owned', models.DecimalField(decimal_places=3, max_digits=5)),
                ('child_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Child', to='mainsite.company')),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='mainsite.company')),
            ],
        ),
        migrations.CreateModel(
            name='operator_through_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('position_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.company')),
                ('position_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.individual')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ManyToManyField(through='mainsite.ownership_through_class', to='mainsite.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='法定代表人',
            field=models.ManyToManyField(through='mainsite.operator_through_class', to='mainsite.individual'),
        ),
    ]
