# Generated by Django 4.0 on 2021-12-28 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='unlinked_position_figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position_title', models.CharField(max_length=50)),
                ('position_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlinked_position_company', to='mainsite.company')),
            ],
        ),
    ]
