# Generated by Django 4.0 on 2021-12-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_unlinked_position_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_relation',
            name='tags_raw',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
