# Generated by Django 3.1 on 2021-09-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20210902_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='backend_string',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='backend_string',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
