# Generated by Django 3.1 on 2021-09-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_remove_company_法定代表人'),
    ]

    operations = [
        migrations.DeleteModel(
            name='operator_through_class',
        ),
    ]
