# Generated by Django 3.1 on 2021-09-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_delete_operator_through_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='法定代表人',
            field=models.ManyToManyField(to='mainsite.individual'),
        ),
    ]
