# Generated by Django 4.0 on 2021-12-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_alter_figure_relation_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_relation',
            name='company_code',
            field=models.CharField(blank=True, help_text='Value listed in QCC API response, carried over for data completeness.', max_length=50, null=True),
        ),
    ]
