# Generated by Django 3.1 on 2021-09-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20210909_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='法定代表人',
        ),
    ]
