# Generated by Django 3.1 on 2021-09-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20210910_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='经营范围',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
