# Generated by Django 3.2.4 on 2021-09-13 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='parent_company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='法定代表人',
        ),
        migrations.RemoveField(
            model_name='company',
            name='经营者',
        ),
    ]
