# Generated by Django 3.2.4 on 2021-09-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_auto_20210913_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='主办券商',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='人员规模',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='企业名称',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='企业类型',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='企业网址',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='会计事务所',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='做市商',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='公司传真',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='公司注册地址',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='公司电子邮箱',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='公司电话',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='办公地址',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='办公地址邮编',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='参保人数',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='实缴资本',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='工商注册号',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='币种',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='律师事务所',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='总经理',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='所属地区',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='所属行业',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='挂牌日期',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='是否上市',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='曾用名',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='机构名称',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='机构状态',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='机构简称',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='机构类型大类',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='机构类型小类',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='注册地址',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='注册地址邮编',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='注册资本',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='注册资本万元',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='登记机关',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='登记状态',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='纳税人识别号',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='纳税人资质',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='组织机构代码',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='经营范围',
            field=models.TextField(default='NULL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='统社会信用代码',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='职工人数',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='英文全称',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='英文名',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='英文简称',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='营业期限',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='董事会秘书',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='董事长',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='董秘传真',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='董秘联系电话',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='董秘邮箱',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='证券代表',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='证券代表传真',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='证券代表电话',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='证券代表邮箱',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='进出口企业代码',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
