# Generated by Django 3.1 on 2021-09-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_company_error_flag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ownership_through_class',
            new_name='ownership',
        ),
    ]
