# Generated by Django 3.1 on 2021-10-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_auto_20211007_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='地址',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='官网',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='电话',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='简介',
            field=models.TextField(default='NULL', max_length=5000),
        ),
        migrations.AddField(
            model_name='company',
            name='邮箱',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
