# Generated by Django 3.1 on 2021-10-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0025_auto_20211018_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_relation',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='company_relation',
            name='registered_cap',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='company_relation',
            name='shouldcapi',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True),
        ),
    ]
