# Generated by Django 3.1 on 2021-10-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0028_company_relation_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_relation',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='company_relation',
            name='percent_total',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Value listed in QCC API response, carried over for data completeness.', max_digits=8, null=True),
        ),
    ]
