# Generated by Django 3.1 on 2021-10-19 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0029_auto_20211019_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_relation',
            name='pulled_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
