# Generated by Django 3.1 on 2021-10-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0030_company_relation_pulled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_relation',
            name='type',
            field=models.CharField(default='NULL', help_text='Value listed in QCC API response, carried over for data completeness.', max_length=200),
        ),
    ]
