# Generated by Django 3.1 on 2021-10-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0032_auto_20211019_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_relation',
            old_name='child_company',
            new_name='target_company',
        ),
    ]
