# Generated by Django 3.1 on 2021-10-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0035_remove_company_relations_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='relations_check',
            field=models.BooleanField(default=False),
        ),
    ]
