# Generated by Django 3.2.9 on 2021-11-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0039_alter_company_backend_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error_report',
            name='error_type',
            field=models.CharField(max_length=50),
        ),
    ]
