# Generated by Django 3.1 on 2021-11-02 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_index_pages_next_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_pages',
            name='last_page_checked',
        ),
    ]
